#include "game_data.h"

Card cardDb[TOTAL_CARDS] = {
    // Tướng 5 Sao
    {1,
     "Lu Bo",
     "Lu Bu",
     5,
     TYPE_VO,
     KINGDOM_QUAN,
     3500,
     2000,
     "anh_game/lubo.png",
     "Chien than vo dich thien ha, tay cam Phuong Thien Hoa Kich.",
     "The unmatched god of war, wielding the Sky Piercer Halberd.",
     {0}},
    {2,
     "Quan Vu",
     "Guan Yu",
     5,
     TYPE_VO,
     KINGDOM_THUC,
     2900,
     1600,
     "anh_game/quanvu.png",
     "Vo thanh dung Thanh Long Yen Nguyet Dao, trung nghia ven toan.",
     "The Martial Saint wielding the Green Dragon Crescent Blade, perfectly "
     "loyal.",
     {0}},
    {3,
     "Trieu Van",
     "Zhao Yun",
     5,
     TYPE_VO,
     KINGDOM_THUC,
     3000,
     1600,
     "anh_game/trieuvan.png",
     "That tien that xuat Truong Ban doc, cuu au chua A Dau.",
     "Charged in and out of Changban seven times to rescue the infant lord.",
     {0}},
    {6,
     "Gia Cat Luong",
     "Zhuge Liang",
     5,
     TYPE_VAN,
     KINGDOM_THUC,
     1700,
     3100,
     "anh_game/giacatluong.png",
     "Ngoa Long tien sinh, muu luoc hon nguoi. Luc xuat Ky Son.",
     "Mr. Sleeping Dragon, possessing unmatched strategy. Launched six "
     "campaigns from Qishan.",
     {0}},

    // Tướng 4 Sao
    {4,
     "Truong Phi",
     "Zhang Fei",
     4,
     TYPE_VO,
     KINGDOM_THUC,
     2700,
     1500,
     "anh_game/truongphi.png",
     "Ho tuong gam vang cau Truong Ban, mot minh chan van quan.",
     "Fierce general who roared at Changban Bridge, stopping a massive army "
     "alone.",
     {0}},
    {5,
     "Dieu Thuyen",
     "Diaochan",
     4,
     TYPE_VAN,
     KINGDOM_QUAN,
     1500,
     2800,
     "anh_game/dieuthuyen.png",
     "Tu dai my nhan, dung lien hoan ke ly gian Dong Trac va Lu Bo.",
     "One of the Four Beauties, used a chain stratagem to divide Dong Zhuo and "
     "Lu Bu.",
     {0}},
    {8,
     "Ma Sieu",
     "Ma Chao",
     4,
     TYPE_VO,
     KINGDOM_THUC,
     3000,
     1600,
     "anh_game/masieu.png",
     "Cam Ma Sieu, uy chan Tay Luong, danh Tao Thao cat rau bo ao.",
     "Ma Chao the Splendid, terror of Xiliang, forced Cao Cao to cut his beard "
     "to escape.",
     {0}},
    {9,
     "Hoang Trung",
     "Huang Zhong",
     4,
     TYPE_VO,
     KINGDOM_THUC,
     2800,
     1600,
     "anh_game/hoangtrung.png",
     "Lao tuong bach phat bach trung, chem Ha Hau Uyen tai Dinh Quan Son.",
     "Veteran archer who never missed, slayed Xiahou Yuan at Mount Dingjun.",
     {0}},
    {11,
     "Ton Sach",
     "Sun Ce",
     4,
     TYPE_VO,
     KINGDOM_NGO,
     2800,
     1600,
     "anh_game/tonsach.png",
     "Tieu Ba Vuong, binh dinh Giang Dong, dung manh vo song.",
     "The Little Conqueror, pacified Jiangdong with unmatched bravery.",
     {0}},
    {16,
     "Tu Ma Y",
     "Sima Yi",
     4,
     TYPE_VAN,
     KINGDOM_NGUY,
     1700,
     3100,
     "anh_game/tumay.png",
     "Lang Co chi tam, muu si nhan nai, dat nen mong cho nha Tan.",
     "Patient strategist with the ambition of a wolf, laid the foundation for "
     "the Jin Dynasty.",
     {0}},
    {17,
     "Tao Thao",
     "Cao Cao",
     4,
     TYPE_VAN,
     KINGDOM_NGUY,
     1700,
     3100,
     "anh_game/taothao.png",
     "Gian hung thoi loan, muu luoc hon nguoi, thong nhat phuong Bac.",
     "Hero of chaos, brilliant strategist who unified Northern China.",
     {0}},
    {18,
     "Chu Du",
     "Zhou Yu",
     4,
     TYPE_VAN,
     KINGDOM_NGO,
     1600,
     2900,
     "anh_game/chudu.png",
     "Dai do doc Dong Ngo, hoa thieu Xich Bich, tai kiem van vo.",
     "Grand Viceroy of Eastern Wu, orchestrated the fire attack at Chibi.",
     {0}},
    {20,
     "Dien Vi",
     "Dian Wei",
     4,
     TYPE_VO,
     KINGDOM_NGUY,
     3100,
     1700,
     "anh_game/dienvi.png",
     "Ho ve trung thanh cua Tao Thao, mot minh chan van quan.",
     "Cao Cao's loyal bodyguard, held off an entire army single-handedly.",
     {0}},
    {22,
     "Hua Chu",
     "Xu Chu",
     4,
     TYPE_VO,
     KINGDOM_NGUY,
     2900,
     1600,
     "anh_game/huachu.png",
     "Ho Si, luc si vo song, loa bo ao dau Ma Sieu.",
     "Tiger Fool, a warrior of immense strength, fought Ma Chao bare-chested.",
     {0}},
    {25,
     "Truong Lieu",
     "Zhang Liao",
     4,
     TYPE_VO,
     KINGDOM_NGUY,
     2900,
     1600,
     "anh_game/truonglieu.png",
     "Uy chan Hop Phi, 800 quan pha 10 van.",
     "Terror of Hefei, defeated an army of 100,000 with only 800 men.",
     {0}},
    {46,
     "Thai Su Tu",
     "Taishi Ci",
     4,
     TYPE_VO,
     KINGDOM_NGO,
     3000,
     1600,
     "anh_game/thaisutu.png",
     "Manh tuong Giang Dong, dau tay doi voi Ton Sach.",
     "Fierce general of Jiangdong, fought Sun Ce to a standstill.",
     {0}},

    // Tướng 3 Sao
    {7,
     "Luu Bi",
     "Liu Bei",
     3,
     TYPE_VAN,
     KINGDOM_THUC,
     1400,
     2600,
     "anh_game/luubi.png",
     "Huyen Duc nhan nghia, sang lap nha Thuc Han.",
     "Virtuous Xuande, founder of the Shu Han kingdom.",
     {0}},
    {10,
     "Ton Quyen",
     "Sun Quan",
     3,
     TYPE_VAN,
     KINGDOM_NGO,
     1500,
     2900,
     "anh_game/tonquyen.png",
     "Bich Nhan Nhi, chua Dong Ngo.",
     "The green-eyed ruler of Eastern Wu.",
     {0}},
    {12,
     "Ha Hau Don",
     "Xiahou Dun",
     3,
     TYPE_VO,
     KINGDOM_NGUY,
     2800,
     1600,
     "anh_game/hahaudon.png",
     "Doc nhan tuong quan, nuot con nguoi giua tran.",
     "One-eyed general who swallowed his own eye during battle.",
     {0}},
    {13,
     "Vien Thieu",
     "Yuan Shao",
     3,
     TYPE_VAN,
     KINGDOM_QUAN,
     1500,
     2900,
     "anh_game/vienthieu.png",
     "Dai chu hau phuong Bac, bai tran Quan Do.",
     "Great warlord of the North, defeated at Guandu.",
     {0}},
    {14,
     "Bang Thong",
     "Pang Tong",
     3,
     TYPE_VAN,
     KINGDOM_THUC,
     1600,
     2900,
     "anh_game/bangthong.png",
     "Phuong So tien sinh, tai tri sanh ngang Gia Cat Luong.",
     "Mr. Fledgling Phoenix, a strategist rivaling Zhuge Liang.",
     {0}},
    {19,
     "Cam Ninh",
     "Gan Ning",
     3,
     TYPE_VO,
     KINGDOM_NGO,
     2600,
     1400,
     "anh_game/camninh.png",
     "Kinh Chau Cam Hung Ba, dung manh tuyet luan.",
     "Fierce pirate-turned-general with bells of terror.",
     {0}},
    {21,
     "Dong Trac",
     "Dong Zhuo",
     3,
     TYPE_VAN,
     KINGDOM_QUAN,
     1500,
     2500,
     "anh_game/dongtrac.png",
     "Bao chua long quyen, khong che thien tu.",
     "Tyrant who hijacked the Han dynasty and controlled the emperor.",
     {0}},
    {23,
     "Nguy Dien",
     "Wei Yan",
     3,
     TYPE_VO,
     KINGDOM_THUC,
     2700,
     1500,
     "anh_game/nguydien.png",
     "Manh tuong phan chu, bi chem theo ke Khong Minh.",
     "Fierce general accused of treason, executed via Zhuge Liang's plot.",
     {0}},
    {24,
     "Quach Gia",
     "Guo Jia",
     3,
     TYPE_VAN,
     KINGDOM_NGUY,
     1500,
     2700,
     "anh_game/quachgia.png",
     "Muu si tai ba yeu menh cua Tao Thao.",
     "Brilliant but short-lived strategist of Cao Cao.",
     {0}},
    {29,
     "Gia Hu",
     "Jia Xu",
     3,
     TYPE_VAN,
     KINGDOM_NGUY,
     1500,
     2700,
     "anh_game/giahu.png",
     "Doc si Gia Hu, muu ke hiem doc.",
     "The venomous strategist, master of ruthless schemes.",
     {0}},
    {32,
     "Khuong Duy",
     "Jiang Wei",
     3,
     TYPE_VO,
     KINGDOM_THUC,
     2800,
     1700,
     "anh_game/khuongduy.png",
     "Truyen nhan cua Gia Cat Luong, 9 lan Bac phat.",
     "Zhuge Liang's successor, launched nine northern expeditions.",
     {0}},
    {34,
     "La Mong",
     "Lu Meng",
     3,
     TYPE_VO,
     KINGDOM_NGO,
     2700,
     1500,
     "anh_game/lamong.png",
     "Bach y qua song danh Kinh Chau, ha Quan Vu.",
     "Crossed the river in white robes to take Jingzhou and defeat Guan Yu.",
     {0}},
    {37,
     "Luc Ton",
     "Lu Xun",
     3,
     TYPE_VAN,
     KINGDOM_NGO,
     1600,
     2900,
     "anh_game/lucton.png",
     "Dai do doc Dong Ngo, hoa thieu doanh trai Di Lang.",
     "Viceroy of Wu, burned Liu Bei's camps at Yiling.",
     {0}},
    {42,
     "Nhan Luong",
     "Yan Liang",
     3,
     TYPE_VO,
     KINGDOM_QUAN,
     2700,
     1400,
     "anh_game/nhanluong.png",
     "Manh tuong Vien Thieu, bi Quan Vu chem tai Bach Ma.",
     "Yuan Shao's fierce general, slain by Guan Yu at Baima.",
     {0}},
    {48,
     "Ton Kien",
     "Sun Jian",
     3,
     TYPE_VO,
     KINGDOM_NGO,
     2800,
     1500,
     "anh_game/tonkien.png",
     "Ho tuong Giang Dong, cha cua Ton Sach va Ton Quyen.",
     "Tiger of Jiangdong, father of Sun Ce and Sun Quan.",
     {0}},
    {52,
     "Truong Cap",
     "Zhang He",
     3,
     TYPE_VO,
     KINGDOM_NGUY,
     2700,
     1600,
     "anh_game/truongcap.png",
     "Ngu Tu Luong Tuong, gioi xoay chuyen tinh the.",
     "One of the Five Elite Generals, master of adaptable tactics.",
     {0}},
    {55,
     "Tuan Uc",
     "Xun Yu",
     3,
     TYPE_VAN,
     KINGDOM_NGUY,
     1500,
     2700,
     "anh_game/tuanuc.png",
     "Vuong Ta chi tai, muu si hang dau Tao Thao.",
     "Cao Cao's top advisor and grand statesman.",
     {0}},
    {57,
     "Van Xu",
     "Wen Chou",
     3,
     TYPE_VO,
     KINGDOM_QUAN,
     2600,
     1400,
     "anh_game/vanxu.png",
     "Manh tuong Vien Thieu, dung cam xung phong.",
     "Brave general of Yuan Shao, charged into battle fearlessly.",
     {0}},

    // Tướng 2 Sao
    {15,
     "Hoa Hung",
     "Hua Xiong",
     2,
     TYPE_VO,
     KINGDOM_QUAN,
     2600,
     1400,
     "anh_game/hoahung.png",
     "Manh tuong Dong Trac, bi Quan Vu chem khi ruou con nong.",
     "General of Dong Zhuo, slain by Guan Yu while his wine was still warm.",
     {0}},
    {27,
     "Chu Thai",
     "Zhou Tai",
     2,
     TYPE_VO,
     KINGDOM_NGO,
     2600,
     1500,
     "anh_game/chuthai.png",
     "Manh tuong Dong Ngo, cuu Ton Quyen thoat hiem.",
     "Wu general who took countless scars to save Sun Quan.",
     {0}},
    {30,
     "Hoang Cai",
     "Huang Gai",
     2,
     TYPE_VO,
     KINGDOM_NGO,
     2500,
     1500,
     "anh_game/hoangcai.png",
     "Lao tuong Dong Ngo, dung kho nhuc ke tai Xich Bich.",
     "Veteran who endured a physical beating to execute a fake defection.",
     {0}},
    {33,
     "Ky Linh",
     "Ji Ling",
     2,
     TYPE_VO,
     KINGDOM_QUAN,
     2600,
     1400,
     "anh_game/kylinh.png",
     "Dai tuong Vien Thuat, cam Tam Tiem Luong Nhat Dao.",
     "General of Yuan Shu, wielded the Three-Point Double-Edged Blade.",
     {0}},
    {35,
     "Lieu Hoa",
     "Liao Hua",
     2,
     TYPE_VO,
     KINGDOM_THUC,
     2400,
     1300,
     "anh_game/lieuhoa.png",
     "Lao tuong Thuc Han, trung thanh son sat.",
     "Loyal veteran general of Shu Han.",
     {0}},
    {36,
     "Lo Tuc",
     "Lu Su",
     2,
     TYPE_VAN,
     KINGDOM_NGO,
     1400,
     2600,
     "anh_game/lotuc.png",
     "Muu si Dong Ngo, chu truong lien minh Ton-Luu.",
     "Diplomatic advisor who advocated for the Sun-Liu alliance.",
     {0}},
    {39,
     "Ma Dai",
     "Ma Dai",
     2,
     TYPE_VO,
     KINGDOM_THUC,
     2500,
     1400,
     "anh_game/madai.png",
     "Em ho Ma Sieu, chem Nguy Dien theo ke Gia Cat Luong.",
     "Cousin of Ma Chao, executed Wei Yan on Zhuge Liang's secret orders.",
     {0}},
    {41,
     "Nhac Tien",
     "Yue Jin",
     2,
     TYPE_VO,
     KINGDOM_NGUY,
     2700,
     1500,
     "anh_game/nhactien.png",
     "Ngu Tu Luong Tuong, tran thu Hop Phi.",
     "One of the Five Elite Generals, stationed at Hefei.",
     {0}},
    {43,
     "Phap Chinh",
     "Fa Zheng",
     2,
     TYPE_VAN,
     KINGDOM_THUC,
     1400,
     2700,
     "anh_game/phapchinh.png",
     "Muu si Luu Bi, bay ke chiem Ich Chau.",
     "Liu Bei's brilliant tactician who helped conquer Yizhou.",
     {0}},
    {44,
     "Quan Binh",
     "Guan Ping",
     2,
     TYPE_VO,
     KINGDOM_THUC,
     2500,
     1400,
     "anh_game/quanbinh.png",
     "Con trai Quan Vu, cung cha tu tran Mach Thanh.",
     "Adopted son of Guan Yu, fought to the death alongside his father.",
     {0}},
    {45,
     "Tao Nhan",
     "Cao Ren",
     2,
     TYPE_VO,
     KINGDOM_NGUY,
     2500,
     1700,
     "anh_game/taonhan.png",
     "Em ho Tao Thao, tran thu Phan Thanh.",
     "Cao Cao's cousin and a formidable defensive commander.",
     {0}},
    {49,
     "Trinh Duc",
     "Cheng Yu",
     2,
     TYPE_VAN,
     KINGDOM_NGUY,
     1400,
     2600,
     "anh_game/trinhduc.png",
     "Muu si Tao Thao, tinh toan sau xa.",
     "Highly capable and pragmatic advisor to Cao Cao.",
     {0}},
    {50,
     "Trinh Pho",
     "Cheng Pu",
     2,
     TYPE_VO,
     KINGDOM_NGO,
     2600,
     1400,
     "anh_game/trinhpho.png",
     "Lao tuong Dong Ngo, phuc vu ba doi ho Ton.",
     "Veteran general who served three generations of the Sun family.",
     {0}},
    {51,
     "Truong Bao",
     "Zhang Bao",
     2,
     TYPE_VO,
     KINGDOM_THUC,
     2500,
     1400,
     "anh_game/truongbao.png",
     "Con Truong Phi, theo Gia Cat Luong Bac phat.",
     "Son of Zhang Fei, marched on the Northern Expeditions.",
     {0}},
    {53,
     "Truong Giac",
     "Zhang Jiao",
     2,
     TYPE_VAN,
     KINGDOM_QUAN,
     1400,
     2700,
     "anh_game/truonggiac.png",
     "Giao chu Thai Binh Dao, tu xung Thien Cong Tuong Quan.",
     "Leader of the Yellow Turbans, proclaimed himself General of Heaven.",
     {0}},
    {56,
     "Tu Hoang",
     "Xu Huang",
     2,
     TYPE_VO,
     KINGDOM_NGUY,
     2700,
     1500,
     "anh_game/tuhoang.png",
     "Ngu Tu Luong Tuong, giai vay Phan Thanh.",
     "Elite Wei general who lifted the siege of Fancheng.",
     {0}},
    {58,
     "Vu Cam",
     "Yu Jin",
     2,
     TYPE_VO,
     KINGDOM_NGUY,
     2600,
     1400,
     "anh_game/vucam.png",
     "Ngu Tu Luong Tuong, dau hang nhuc nha.",
     "Once an elite general, his reputation was ruined by surrendering.",
     {0}},

    // Tướng 1 Sao
    {26,
     "Chau Thuong",
     "Zhou Cang",
     1,
     TYPE_VO,
     KINGDOM_THUC,
     2300,
     1300,
     "anh_game/chauthuong.png",
     "Ho ve trung thanh cua Quan Vu.",
     "Loyal shield-bearer of Guan Yu.",
     {0}},
    {28,
     "Chu Tuan",
     "Zhu Jun",
     1,
     TYPE_VO,
     KINGDOM_QUAN,
     2400,
     1500,
     "anh_game/chutuan.png",
     "Danh tuong nha Han, dep loan Khan Vang.",
     "Han imperial general who fought the Yellow Turbans.",
     {0}},
    {31,
     "Hoang Phu Tung",
     "Huangfu Song",
     1,
     TYPE_VO,
     KINGDOM_QUAN,
     2400,
     1500,
     "anh_game/hoangphutung.png",
     "Danh tuong nha Han, dep tac Khan Vang.",
     "Famous Han commander who quelled the Yellow Turban Rebellion.",
     {0}},
    {38,
     "Lu Thuc",
     "Lu Zhi",
     1,
     TYPE_VAN,
     KINGDOM_QUAN,
     1300,
     2500,
     "anh_game/luthuc.png",
     "Thay cua Luu Bi, hai noi dai nho.",
     "Liu Bei's mentor and a great scholar of the Han empire.",
     {0}},
    {40,
     "My Truc",
     "Mi Zhu",
     1,
     TYPE_VAN,
     KINGDOM_THUC,
     1200,
     2300,
     "anh_game/mychuc.png",
     "Phu thuong giau co, tai tro Luu Bi dung nghiep.",
     "Wealthy merchant who heavily funded Liu Bei's early campaigns.",
     {0}},
    {47,
     "Ton Can",
     "Sun Qian",
     1,
     TYPE_VAN,
     KINGDOM_THUC,
     1200,
     2200,
     "anh_game/toncan.png",
     "Tung si trung thanh cua Luu Bi, ngoai giao gioi.",
     "Loyal follower of Liu Bei, skilled in diplomacy.",
     {0}},
    {54,
     "Truong Luong",
     "Zhang Liang",
     1,
     TYPE_VO,
     KINGDOM_QUAN,
     2400,
     1500,
     "anh_game/truongluong.png",
     "Nhan Cong Tuong Quan, em Truong Giac, khoi loan Khan Vang.",
     "General of the People, brother of Zhang Jiao.",
     {0}}};

Texture2D bgTexture = {0};
Texture2D menuTexture = {0};
Texture2D cardBackTexture = {0};

void LoadAllCardTextures() {
  bgTexture = LoadTexture("anh_game/sandau.png");
  SetTextureFilter(bgTexture, TEXTURE_FILTER_BILINEAR);

  menuTexture = LoadTexture("anh_game/menu.png");
  SetTextureFilter(menuTexture, TEXTURE_FILTER_BILINEAR);

  cardBackTexture = LoadTexture("anh_game/matsau.png");

  for (int i = 0; i < TOTAL_CARDS; i++) {
    cardDb[i].texture = LoadTexture(cardDb[i].imgPath);
  }
}

void UnloadAllCardTextures() {
  UnloadTexture(bgTexture);
  UnloadTexture(menuTexture);
  UnloadTexture(cardBackTexture);

  for (int i = 0; i < TOTAL_CARDS; i++) {
    UnloadTexture(cardDb[i].texture);
  }
}

Music bgmMenu = {0};
Music bgmBattle = {0};
Music bgmWin = {0};
Music bgmLose = {0};

void LoadAllMusic() {
    bgmMenu = LoadMusicStream("nhacgame/nhacmenu.mp3");
    bgmBattle = LoadMusicStream("nhacgame/nhactrongtran.mp3");
    bgmWin = LoadMusicStream("nhacgame/nhacthangtran.mp3");
    bgmLose = LoadMusicStream("nhacgame/nhacthuatran.mp3");
}

void UnloadAllMusic() {
    UnloadMusicStream(bgmMenu);
    UnloadMusicStream(bgmBattle);
    UnloadMusicStream(bgmWin);
    UnloadMusicStream(bgmLose);
}